"""Add a title field

Revision ID: 88a8cb25cf37
Revises: fb02a2f6bee9
Create Date: 2016-12-27 16:50:21.172984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a8cb25cf37'
down_revision = 'fb02a2f6bee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
