version: '2'

volumes:
  wts_database:
    driver: local

  wts_videos:
    driver: local


services:
  wts-postgres:
    image: postgres:9.6
    container_name: wts-postgres
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - wts_database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user

  wts-rabbit:
    image: rabbitmq:3.6
    container_name: wts-rabbit
    hostname: wts-rabbit

  wts-nginx:
    image: nginx:1.11
    container_name: wts-nginx
    hostname: wts-nginx
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
      - wts_videos:/www/videos/
    ports:
      - "8080:80"
    environment:
      NGINX_PORT: 80
    links:
      - wts-api

  wts-worker:
    container_name: wts-worker
    build:
      context: .
      dockerfile: ./wts_worker/Dockerfile
    volumes:
      - ./credentials.yaml:/etc/credentials.yaml:ro
      - wts_videos:/videos/
      - .:/code
    links:
      - wts-postgres
      - wts-rabbit

  wts-api:
    container_name: wts-api
    build:
      context: .
      dockerfile: ./wts_api/Dockerfile
    volumes:
      - ./credentials.yaml:/etc/credentials.yaml:ro
      - wts_videos:/videos/
      - .:/code
    links:
      - wts-postgres
      - wts-rabbit
      - wts-worker
