"""Add video title column

Revision ID: 7631bc795be3
Revises: fbc89a453a28
Create Date: 2016-12-20 23:05:49.854726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7631bc795be3'
down_revision = 'fbc89a453a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
